"""Analytics package for operational, agent, resolution, rating, and SLA metrics."""

from app.analytics.agents import get_agent_performance
from app.analytics.aggregations import (
    get_rating_analysis,
    get_resolution_time_analysis,
    get_ticket_summary,
    get_unresolved_ticket_analysis,
)
from app.analytics.metrics import (
    get_average_customer_rating,
    get_average_rating_by_agent,
    get_average_rating_by_category,
    get_average_rating_by_priority,
    get_average_resolution_time,
    get_average_response_time,
    get_critical_unresolved_count,
    get_critical_unresolved_over_24h,
    get_high_priority_unresolved_count,
    get_high_priority_unresolved_over_24h,
    get_median_resolution_time,
    get_median_response_time,
    get_rating_distribution,
    get_resolution_time_by_agent,
    get_resolution_time_by_category,
    get_resolution_time_by_priority,
    get_response_time_by_agent,
    get_response_time_by_category,
    get_response_time_by_priority,
    get_ticket_count_by_agent,
    get_ticket_count_by_category,
    get_ticket_count_by_priority,
    get_ticket_count_by_status,
    get_total_tickets,
    get_unresolved_by_agent,
    get_unresolved_by_category,
    get_unresolved_by_priority,
    get_unresolved_over_24h,
    get_unresolved_ticket_count,
)

__all__ = [
    # Metrics
    "get_total_tickets",
    "get_ticket_count_by_status",
    "get_ticket_count_by_priority",
    "get_ticket_count_by_category",
    "get_ticket_count_by_agent",
    "get_unresolved_ticket_count",
    "get_unresolved_by_priority",
    "get_unresolved_by_category",
    "get_unresolved_by_agent",
    "get_critical_unresolved_count",
    "get_high_priority_unresolved_count",
    "get_average_response_time",
    "get_median_response_time",
    "get_response_time_by_priority",
    "get_response_time_by_category",
    "get_response_time_by_agent",
    "get_average_resolution_time",
    "get_median_resolution_time",
    "get_resolution_time_by_priority",
    "get_resolution_time_by_category",
    "get_resolution_time_by_agent",
    "get_average_customer_rating",
    "get_rating_distribution",
    "get_average_rating_by_agent",
    "get_average_rating_by_priority",
    "get_average_rating_by_category",
    "get_unresolved_over_24h",
    "get_high_priority_unresolved_over_24h",
    "get_critical_unresolved_over_24h",
    # Agent performance
    "get_agent_performance",
    # Composite aggregations
    "get_ticket_summary",
    "get_unresolved_ticket_analysis",
    "get_resolution_time_analysis",
    "get_rating_analysis",
]
